### ISSUE TITLE
Reference field marked as optional but can cause duplicate control names

### ISSUE THREAD

**Issue by kawamonkey-eso** [Baertram/LibAddonMenuOrderListBox#2]
**Steps to reproduce:**

- Create two "orderlistbox" controls without reference specified
- Load both controls into UI

Since line 395 of the Lua code, `local controlName = control:GetName()`, will assign an empty string, the scroll list control will always be created with name `_OrderListBox` a few lines down, causing duplicate naming if multiple controls haven't got a reference specified.

**Comment by Baertram** [comment]
Ah yeah, LAM's function to create a control dos not always return some name string:
local control = util.CreateLabelAndContainerControl(parent, orderListBoxData, controlName)

Thanks for the reminder, will add some internal naming template + counter

**Comment by Baertram** [comment]
```
function LAMCreateControl.orderlistbox(parent, orderListBoxData, controlName)
    orderListBoxCounter = orderListBoxCounter + 1
    --GitHub issue #2 controlName ("reference") is not always provided so duplicate names could occur -> Prevent those
    controlName = controlName or string.format(orderListBoxNameTemplate, tostring(orderListBoxCounter))
    local control = util.CreateLabelAndContainerControl(parent, orderListBoxData, controlName)
```
