### ISSUE TITLE
Reference property not working since update on 2023-11-13

### ISSUE THREAD

**Issue by t4cmyk** [Baertram/LibAddonMenuOrderListBox#5]
Since the update on 2023-11-13 the reference property is being ignored and the global object reference will always be "LAMOrderListBox_1", "LAMOrderListBox_2", etc.

A possible fix is to change line 1074 from
`    controlName = controlName or string.format(orderListBoxNameTemplate, tostring(orderListBoxCounter))`
to:
`    controlName = controlName or orderListBoxData.reference or string.format(orderListBoxNameTemplate, tostring(orderListBoxCounter))`

**Comment by Baertram** [comment]
Thanks for the report.
I thought the function CreateBaseControl(parent, controlData, controlName) in LAM 2.0 util does handle that but obviously it is only taking "controlName" if it's not nil

I need to find a better way
